---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - yarn install

jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:

        - npx expo login -u 'brayhanjaramillo' -p 'andresjc.;'
        - npx expo publish --non-interactive
