language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install -g expo-cli@latest
  - npm install
  - npm install jest-expo
  - npm install -g expo-cli
  
script:
  - npm ci

jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - yarn start