export const RAZA = [
	{ label: 'Otro', value: 'Otro' },
	{ label: 'Alano', value: 'Alano' },
	{ label: 'Alaskan Malamute', value: 'Alaskan Malamute' },
	{ label: 'American Staffordshire Terrier', value: 'American Staffordshire Terrier' },
	{ label: 'American Water Spaniel', value: 'American Water Spaniel' },
	{ label: 'Antiguo Pastor Inglés', value: 'Antiguo Pastor Inglés' },
	{ label: 'Basset Azul de Gaseogne', value: 'Basset Azul de Gaseogne' },
	{ label: 'Basset Hound', value: 'Basset Hound' },
	{ label: 'Basset leonado de Bretaña', value: 'Basset leonado de Bretaña' },
	{ label: 'Beagle', value: 'Beagle' },
	{ label: 'Bearded Collie', value: 'Bearded Collie' },
	{ label: 'Bichón Maltés', value: 'Bichón Maltés' },
	{ label: 'Bobtail', value: 'Bobtail' },
	{ label: 'Border Collie', value: 'Border Collie' },
	{ label: 'Boston Terrier', value: 'Boston Terrier' },
	{ label: 'Boxer', value: 'Boxer' },
	{ label: 'Bull Terrier', value: 'Bull Terrier' },
	{ label: 'Bulldog Americano', value: 'Bulldog Americano' },
	{ label: 'Bulldog Francés', value: 'Bulldog Francés' },
	{ label: 'Bulldog Inglés', value: 'Bulldog Inglés' },
	{ label: 'Caniche', value: 'Caniche' },
	{ label: 'Carlino', value: 'Carlino' },
	{ label: 'Chihuahua', value: 'Chihuahua' },
	{ label: 'Cirneco del Etna', value: 'Cirneco del Etna' },
	{ label: 'Chow Chow', value: 'Chow Chow' },
	{ label: 'Cocker Spaniel Americano', value: 'Cocker Spaniel Americano' },
	{ label: 'Cocker Spaniel Inglés', value: 'Cocker Spaniel Inglés' },
	{ label: 'Criollo', value: 'Criollo' },
	{ label: 'Dálmata', value: 'Dálmata' },
	{ label: 'Dobermann', value: 'Dobermann' },
	{ label: 'Dogo Alemán', value: 'Dogo Alemán' },
	{ label: 'Dogo Argentino', value: 'Dogo Argentino' },
	{ label: 'Dogo de Burdeos', value: 'Dogo de Burdeos' },
	{ label: 'Finlandés', value: 'Finlandés' },
	{ label: 'Fox Terrier de pelo liso', value: 'Fox Terrier de pelo liso' },
	{ label: 'Fox Terrier', value: 'Fox Terrier' },
	{ label: 'Foxhound Americano', value: 'Foxhound Americano' },
	{ label: 'Foxhound Inglés', value: 'Foxhound Inglés' },
	{ label: 'Galgo Afgano', value: 'Galgo Afgano' },
	{ label: 'Gigante de los Pirineos', value: 'Gigante de los Pirineos' },
	{ label: 'Golden Retriever', value: 'Golden Retriever' },
	{ label: 'Gos d Atura', value: 'Gos d Atura' },
	{ label: 'Gran Danés', value: 'Gran Danés' },
	{ label: 'Husky Siberiano', value: 'Husky Siberiano' },
	{ label: 'Laika de Siberia Occidental', value: 'Laika de Siberia Occidental' },
	{ label: 'Laika Ruso-europeo', value: 'Laika Ruso-europeo' },
	{ label: 'Labrador Retriever', value: 'Labrador Retriever' },
	{ label: 'Mastín del Pirineo', value: 'Mastín del Pirineo' },
	{ label: 'Mastin del Tibet', value: 'Mastin del Tibet' },
	{ label: 'Mastín Español', value: 'Mastín Español' },
	{ label: 'Mastín Napolitano', value: 'Mastín Napolitano' },
	{ label: 'Pastor Alemán', value: 'Pastor Alemán' },
	{ label: 'Pastor Australiano', value: 'Pastor Australiano' },
	{ label: 'Pastor Belga', value: 'Pastor Belga' },
	{ label: 'Pastor de Brie', value: 'Pastor de Brie' },
	{ label: 'Pastor de los Pirineos de Cara Rosa', value: 'Pastor de los Pirineos de Cara Rosa' },
	{ label: 'Pekinés', value: 'Pekinés' },
	{ label: 'Perdiguero Chesapeake Bay', value: 'Perdiguero Chesapeake Bay' },
	{ label: 'Perdiguero de Drentse', value: 'Perdiguero de Drentse' },
	{ label: 'Perdiguero de Pelo lido', value: 'Perdiguero de Pelo lido' },
	{ label: 'Perdiguero de pelo rizado', value: 'Perdiguero de pelo rizado' },
	{ label: 'Perdiguero Portugués', value: 'Perdiguero Portugués' },
	{ label: 'Pitbull', value: 'Pitbull' },
	{ label: 'Podenco Ibicenco', value: 'Podenco Ibicenco' },
	{ label: 'Podenco Portugués', value: 'Podenco Portugués' },
	{ label: 'presa canario', value: 'presa canario' },
	{ label: 'Presa Mallorquin', value: 'Presa Mallorquin' },
	{ label: 'Rottweiler', value: 'Rottweiler' },
	{ label: 'Rough Collie', value: 'Rough Collie' },
	{ label: 'Sabueso Español', value: 'Sabueso Español' },
	{ label: 'Sabueso Hélenico', value: 'Sabueso Hélenico' },
	{ label: 'Sabueso Italiano', value: 'Sabueso Italiano' },
	{ label: 'Sabueso Suizo', value: 'Sabueso Suizo' },
	{ label: 'Samoyedo', value: 'Samoyedo' },
	{ label: 'San Bernardo', value: 'San Bernardo' },
	{ label: 'Scottish Terrier', value: 'Scottish Terrier' },
	{ label: 'Setter Irlandés', value: 'Setter Irlandés' },
	{ label: 'Shar Pei', value: 'Shar Pei' },
	{ label: 'Shiba Inu', value: 'Shiba Inu' },
	{ label: 'Siberian Husky', value: 'Siberian Husky' },
	{ label: 'Staffordshire Bull Terrier', value: 'Staffordshire Bull Terrier' },
	{ label: 'Teckel', value: 'Teckel' },
	{ label: 'Terranova', value: 'Terranova' },
	{ label: 'Terrier Australiano', value: 'Terrier Australiano' },
	{ label: 'Terrier Escocés', value: 'Terrier Escocés' },
	{ label: 'Terrier Irlandés', value: 'Terrier Irlandés' },
	{ label: 'Terrier Japonés', value: 'Terrier Japonés' },
	{ label: 'Terrier Negro Ruso', value: 'Terrier Negro Ruso' },
	{ label: 'Terrier Norfolk', value: 'Terrier Norfolk' },
	{ label: 'Terrier Norwich', value: 'Terrier Norwich' },
	{ label: 'Yorkshire Terrier', value: 'Yorkshire Terrier' }
];

export const TYPE_SEX = [ { label: 'Hembra', value: 'Hembra' }, { label: 'Macho', value: 'Macho' } ];

export const TYPE_PETS = [
	{
		label: 'Perro',
		value: 'Perro'
	},
	{
		label: 'Gato',
		value: 'Gato'
	},
	{
		label: 'Cerdo',
		value: 'Cerdo'
	},
	{
		label: 'Otro',
		value: 'Otro'
	}
];

export const RAZA_CAT = [
	{ label: 'Abisinio', value: 'Abisinio' },
	{ label: 'Africano doméstico', value: 'Africano doméstico' },
	{ label: 'American Curl', value: 'American Curl' },
	{ label: 'American shorthair', value: 'American shorthair' },
	{ label: 'American wirehair', value: 'American wirehair' },
	{ label: 'Angora turco', value: 'Angora turco' },
	{ label: 'Aphrodite-s Giants', value: 'Aphrodite-s Giants' },
	{ label: 'Australian Mist', value: 'Australian Mist' },
	{ label: 'Azul ruso', value: 'Azul ruso' },
	{ label: 'Bengala', value: 'Bengala' },
	{ label: 'Bobtail japonés', value: 'Bobtail japonés' },
	{ label: 'Bombay', value: 'Bombay' },
	{ label: 'Bosque de Noruega', value: 'Bosque de Noruega' },
	{ label: 'Brazilian Shorthair', value: 'Brazilian Shorthair' },
	{ label: 'British Shorthair', value: 'British Shorthair' },
	{ label: 'Burmés', value: 'Burmés' },
	{ label: 'Burmilla', value: 'Burmilla' },
	{ label: 'California Spangled', value: 'California Spangled' },
	{ label: 'Ceylon', value: 'Ceylon' },
	{ label: 'Chartreux', value: 'Chartreux' },
	{ label: 'Cornish rex', value: 'Cornish rex' },
	{ label: 'Cymric', value: 'Cymric' },
	{ label: 'Deutsch Langhaar', value: 'Deutsch Langhaar' },
	{ label: 'Devon rex', value: 'Devon rex' },
	{ label: 'Don Sphynx', value: 'Don Sphynx' },
	{ label: 'Dorado africano', value: 'Dorado africano' },
	{ label: 'Europeo común', value: 'Europeo común' },
	{ label: 'Gato exótico', value: 'Gato exótico' },
	{ label: 'German Rex', value: 'German Rex' },
	{ label: 'Habana brown', value: 'Habana brown' },
	{ label: 'Himalayo', value: 'Himalayo' },
	{ label: 'Khao Manee', value: 'Khao Manee' },
	{ label: 'Korat', value: 'Korat' },
	{ label: 'Maine Coon', value: 'Maine Coon' },
	{ label: 'Manx', value: 'Manx' },
	{ label: 'Mau egipcio', value: 'Mau egipcio' },
	{ label: 'Munchkin', value: 'Munchkin' },
	{ label: 'Ocicat', value: 'Ocicat' },
	{ label: 'Ojos azules', value: 'Ojos azules' },
	{ label: 'Oriental', value: 'Oriental' },
	{ label: 'Oriental de pelo largo', value: 'Oriental de pelo largo' },
	{ label: 'Persa', value: 'Persa' },
	{ label: 'Peterbald', value: 'Peterbald' },
	{ label: 'Pixi Bob', value: 'Pixi Bob' },
	{ label: 'Ragdoll', value: 'Ragdoll' },
	{ label: 'Sagrado de Birmania', value: 'Sagrado de Birmania' },
	{ label: 'Scottish Fold', value: 'Scottish Fold' },
	{ label: 'Selkirk rex', value: 'Selkirk rex' },
	{ label: 'Serengeti', value: 'Serengeti' },
	{ label: 'Seychellois', value: 'Seychellois' },
	{ label: 'Siamés', value: 'Siamés' },
	{ label: 'Siamés Moderno', value: 'Siamés Moderno' },
	{ label: 'Siamés Tradicional', value: 'Siamés Tradicional' },
	{ label: 'Siberiano', value: 'Siberiano' },
	{ label: 'Snowshoe', value: 'Snowshoe' },
	{ label: 'Sphynx', value: 'Sphynx' },
	{ label: 'Tonkinés', value: 'Tonkinés' },
	{ label: 'Van Turco', value: 'Van Turco' }
];
