export const RAZA = [
	{ label: 'Otro', value: 'Otro' },
	{ label: 'Alano', value: 'Alano' },
	{ label: 'Alaskan Malamute', value: 'Alaskan_Malamute' },
	{ label: 'American Staffordshire Terrier', value: 'American_Staffordshire_Terrier' },
	{ label: 'American Water Spaniel', value: 'American_Water_Spaniel' },
	{ label: 'Antiguo Pastor Inglés', value: 'Antiguo_Pastor_Inglés' },
	{ label: 'Basset Azul de Gaseogne', value: 'Basset_Azul_de_Gaseogne' },
	{ label: 'Basset Hound', value: 'Basset_Hound' },
	{ label: 'Basset leonado de Bretaña', value: 'Basset_leonado_de_Bretaña' },
	{ label: 'Beagle', value: 'Beagle' },
	{ label: 'Bearded Collie', value: 'Bearded_Collie' },
	{ label: 'Bichón Maltés', value: 'Bichón_Maltés' },
	{ label: 'Bobtail', value: 'Bobtail' },
	{ label: 'Border Collie', value: 'Border_Collie' },
	{ label: 'Boston Terrier', value: 'Boston_Terrier' },
	{ label: 'Boxer', value: 'Boxer' },
	{ label: 'Bull Terrier', value: 'Bull_Terrier' },
	{ label: 'Bulldog Americano', value: 'Bulldog_Americano' },
	{ label: 'Bulldog Francés', value: 'Bulldog_Francés' },
	{ label: 'Bulldog Inglés', value: 'Bulldog_Inglés' },
	{ label: 'Caniche', value: 'Caniche' },
	{ label: 'Carlino', value: 'Carlino' },
	{ label: 'Chihuahua', value: 'Chihuahua' },
	{ label: 'Cirneco del Etna', value: 'Cirneco_del_Etna' },
	{ label: 'Chow Chow', value: 'Chow_Chow' },
	{ label: 'Cocker Spaniel Americano', value: 'Cocker_Spaniel_Americano' },
	{ label: 'Cocker Spaniel Inglés', value: 'Cocker_Spaniel_Inglés' },
	{ label: 'Criollo', value: 'Criollo' },
	{ label: 'Dálmata', value: 'Dálmata' },
	{ label: 'Dobermann', value: 'Dobermann' },
	{ label: 'Dogo Alemán', value: 'Dogo_Alemán' },
	{ label: 'Dogo Argentino', value: 'Dogo_Argentino' },
	{ label: 'Dogo de Burdeos', value: 'Dogo_de_Burdeos' },
	{ label: 'Finlandés', value: 'Finlandés' },
	{ label: 'Fox Terrier de pelo liso', value: 'Fox_Terrier_de_pelo_liso' },
	{ label: 'Fox Terrier', value: 'Fox_Terrier' },
	{ label: 'Foxhound Americano', value: 'Foxhound_Americano' },
	{ label: 'Foxhound Inglés', value: 'Foxhound_Inglés' },
	{ label: 'Galgo Afgano', value: 'Galgo_Afgano' },
	{ label: 'Gigante de los Pirineos', value: 'Gigante_de_los_Pirineos' },
	{ label: 'Golden Retriever', value: 'Golden_Retriever' },
	{ label: 'Gos d Atura', value: 'Gos_d_Atura' },
	{ label: 'Gran Danés', value: 'Gran_Danés' },
	{ label: 'Husky Siberiano', value: 'Husky_Siberiano' },
	{ label: 'Laika de Siberia Occidental', value: 'Laika_de_Siberia_Occidental' },
	{ label: 'Laika Ruso-europeo', value: 'Laika_Ruso-europeo' },
	{ label: 'Labrador Retriever', value: 'Labrador_Retriever' },
	{ label: 'Mastín del Pirineo', value: 'Mastín_del_Pirineo' },
	{ label: 'Mastin del Tibet', value: 'Mastin_del_Tibet' },
	{ label: 'Mastín Español', value: 'Mastín_Español' },
	{ label: 'Mastín Napolitano', value: 'Mastín_Napolitano' },
	{ label: 'Pastor Alemán', value: 'Pastor_Alemán' },
	{ label: 'Pastor Australiano', value: 'Pastor_Australiano' },
	{ label: 'Pastor Belga', value: 'Pastor_Belga' },
	{ label: 'Pastor de Brie', value: 'Pastor_de_Brie' },
	{ label: 'Pastor de los Pirineos de Cara Rosa', value: 'Pastor_de_los_Pirineos_de_Cara_Rosa' },
	{ label: 'Pekinés', value: 'Pekinés' },
	{ label: 'Perdiguero Chesapeake Bay', value: 'Perdiguero_Chesapeake_Bay' },
	{ label: 'Perdiguero de Drentse', value: 'Perdiguero_de_Drentse' },
	{ label: 'Perdiguero de Pelo lido', value: 'Perdiguero_de_Pelo_lido' },
	{ label: 'Perdiguero de pelo rizado', value: 'Perdiguero_de_pelo_rizado' },
	{ label: 'Perdiguero Portugués', value: 'Perdiguero_Portugués' },
	{ label: 'Pitbull', value: 'Pitbull' },
	{ label: 'Podenco Ibicenco', value: 'Podenco_Ibicenco' },
	{ label: 'Podenco Portugués', value: 'Podenco_Portugués' },
	{ label: 'presa canario', value: 'presa_canario' },
	{ label: 'Presa Mallorquin', value: 'Presa_Mallorquin' },
	{ label: 'Rottweiler', value: 'Rottweiler' },
	{ label: 'Rough Collie', value: 'Rough_Collie' },
	{ label: 'Sabueso Español', value: 'Sabueso_Español' },
	{ label: 'Sabueso Hélenico', value: 'Sabueso_Hélenico' },
	{ label: 'Sabueso Italiano', value: 'Sabueso_Italiano' },
	{ label: 'Sabueso Suizo', value: 'Sabueso_Suizo' },
	{ label: 'Samoyedo', value: 'Samoyedo' },
	{ label: 'San Bernardo', value: 'San_Bernardo' },
	{ label: 'Scottish Terrier', value: 'Scottish_Terrier' },
	{ label: 'Setter Irlandés', value: 'Setter_Irlandés' },
	{ label: 'Shar Pei', value: 'Shar_Pei' },
	{ label: 'Shiba Inu', value: 'Shiba_Inu' },
	{ label: 'Siberian Husky', value: 'Siberian_Husky' },
	{ label: 'Staffordshire Bull Terrier', value: 'Staffordshire_Bull_Terrier' },
	{ label: 'Teckel', value: 'Teckel' },
	{ label: 'Terranova', value: 'Terranova' },
	{ label: 'Terrier Australiano', value: 'Terrier_Australiano' },
	{ label: 'Terrier Escocés', value: 'Terrier_Escocés' },
	{ label: 'Terrier Irlandés', value: 'Terrier_Irlandés' },
	{ label: 'Terrier Japonés', value: 'Terrier_Japonés' },
	{ label: 'Terrier Negro Ruso', value: 'Terrier_Negro_Ruso' },
	{ label: 'Terrier Norfolk', value: 'Terrier_Norfolk' },
	{ label: 'Terrier Norwich', value: 'Terrier_Norwich' },
	{ label: 'Yorkshire Terrier', value: 'Yorkshire_Terrier' }
];
